---

- hosts: all
  become: true
  tasks:

  - name: update repos
    apt:
      update_cache: yes
    when: ansible_distribution == "Debian"

  - name: install apache2 package
    apt:
      name: apache2
    when: ansible_distribution == "Debian"


  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Debian"
