---
- name: Install zsh and configure for all users
  hosts: local
  become: true

  vars:
    zshrc_path: ".zshrc"  # Path relative to playbook's files/ directory

  tasks:

    - name: Ensure required packages are installed
      apt:
        name:
          - git
          - zsh
          - btop
          - wget
          - curl
          - nala
        state: latest
        update_cache: yes

    - name: Clone zsh-syntax-highlighting
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: /usr/share/zsh-syntax-highlighting
        update: yes

    - name: Clone zsh-autosuggestions
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions.git
        dest: /usr/share/zsh-autosuggestions
        update: yes

    - name: Get list of local users (UID ≥ 1000 and valid shell)
      command: >
        awk -F: '$3 >= 1000 && $7 ~ /(bash|zsh|sh)$/ { print $1 }' /etc/passwd
      register: local_users_raw
      changed_when: false

    - name: Set fact for user list
      set_fact:
        local_users: "{{ local_users_raw.stdout_lines }}"

    - name: Deploy .zshrc config for each user
      copy:
        src: "{{ zshrc_path }}"
        dest: "/home/{{ item }}/.zshrc"
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: '0644'
      loop: "{{ local_users }}"
      loop_control:
        label: "{{ item }}"

    - name: Set zsh as default shell for each user
      user:
        name: "{{ item }}"
        shell: /usr/bin/zsh
      loop: "{{ local_users }}"

- name: Deploy KDE keyboard shortcuts to all local users
  hosts: local
  become: true

  vars:
    shortcut_file: kglobalshortcutsrc
    users: "{{ lookup('pipe', \"awk -F: '$3 >= 1000 && $7 ~ /(bash|zsh|sh)$/ { print $1 }' /etc/passwd\") | split('\n') }}"

  tasks:

    - name: Ensure .config directory exists for each user
      file:
        path: "/home/{{ item }}/.config"
        state: directory
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: '0755'
      loop: "{{ users }}"
      when: item != 'nobody'

    - name: Deploy custom kglobalshortcutsrc for each user
      copy:
        src: "{{ shortcut_file }}"
        dest: "/home/{{ item }}/.config/kglobalshortcutsrc"
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: '0644'
      loop: "{{ users }}"
      when: item != 'nobody'

    - name: Reload KDE shortcuts via qdbus if X11 session active
      become: false
      shell: |
        qdbus org.kde.kglobalaccel /component/org.kde.konsole reloadConfig || true
      environment:
        DISPLAY: ":0"
        XAUTHORITY: "/home/{{ item }}/.Xauthority"
      loop: "{{ users }}"

- name: Set KDE Plasma wallpaper for all users
  hosts: local
  become: true

  vars:
    wallpaper_path: "/usr/share/wallpapers/my_wallpaper.jpg"

  tasks:

    - name: Get list of users with home directories
      command: >
        awk -F: '$3 >= 1000 && $7 ~ /(bash|zsh|sh)$/ { print $1 }' /etc/passwd
      register: local_users_raw
      changed_when: false

    - name: Set fact with list of users
      set_fact:
        local_users: "{{ local_users_raw.stdout_lines }}"

    - name: Ensure wallpaper exists on remote
      copy:
        src: files/wallpaper.jpg
        dest: "{{ wallpaper_path }}"
        mode: '0644'

- name: Set KDE Plasma wallpaper for each user
  blockinfile:
    path: "/home/{{ item }}/.config/plasma-org.kde.plasma.desktop-appletsrc"
    marker: "# {mark} Ansible managed wallpaper block"
    block: |
      [Containments][1][Wallpaper][org.kde.image][General]
      Image=file://{{ wallpaper_path }}
  become_user: "{{ item }}"
  loop: "{{ local_users }}"

#    - name: Restart Plasma Shell to apply wallpaper for each user
#      shell: |
#        qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript \
#          "var allDesktops = desktops(); for (i=0;i<allDesktops.length;i++) { d = allDesktops[i]; d.wallpaperPlugin = 'org.kde.image'; d.currentConfigGroup = Array('Wallpaper', 'org.kde.image', 'General'); d.writeConfig('Image', 'file://{{ wallpaper_path }}') }"
#      become_user: "{{ item }}"
#      environment:
#        DISPLAY: ":0"
#        XAUTHORITY: "/home/{{ item }}/.Xauthority"
#      loop: "{{ local_users }}"


- name: Configure keybindings per user
  hosts: local
  become: true
  vars:
    font_family: "Caskaydia Mono"
    font_size: "10"
    shortcut_file: kglobalshortcutsrc  # Must be present in playbook's `files/` directory

  tasks:
    - name: Get list of local users with valid shells
      command: >
        awk -F: '$3 >= 1000 && $7 ~ /(bash|zsh|sh)$/ { print $1 }' /etc/passwd
      register: local_users_raw
      changed_when: false

    - name: Set fact with list of users
      set_fact:
        local_users: "{{ local_users_raw.stdout_lines }}"

    - name: Ensure .config exists for each user
      file:
        path: "/home/{{ item }}/.config"
        state: directory
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: '0755'
      loop: "{{ local_users }}"

    - name: Deploy KDE global shortcuts for each user
      copy:
        src: "{{ shortcut_file }}"
        dest: "/home/{{ item }}/.config/kglobalshortcutsrc"
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: '0644'
      loop: "{{ local_users }}"

    - name: Reload KDE shortcuts via qdbus (per user)
      shell: |
        qdbus org.kde.kglobalaccel /component/org.kde.konsole reloadConfig || true
      environment:
        DISPLAY: ":0"
        XAUTHORITY: "/home/{{ item }}/.Xauthority"
      become: false
      loop: "{{ local_users }}"
      ignore_errors: true

    - name: Fallback Reload KDE shortcuts as root with runuser
      shell: |
        runuser -l {{ item }} -c 'DISPLAY=:0 XAUTHORITY=/home/{{ item }}/.Xauthority qdbus org.kde.kglobalaccel /component/org.kde.konsole reloadConfig || true'
      loop: "{{ local_users }}"
      ignore_errors: true

- name: Install CascadiaMono Nerd Font and Apply Breeze Dark Theme
  hosts: localhost
  become: true
  vars:
    font_url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/CascadiaMono.zip"
    font_dest_dir: "/usr/local/share/fonts/cascadiamono"
    font_temp_zip: "/tmp/CascadiaMono.zip"
    kde_user_config_dir: "/home/{{ ansible_user_id }}/.config"

  tasks:
    - name: Ensure unzip and fonts directory exist
      apt:
        name: unzip
        state: present
        update_cache: true

    - name: Create destination font directory
      file:
        path: "{{ font_dest_dir }}"
        state: directory
        mode: '0755'

    - name: Download CascadiaMono Nerd Font
      get_url:
        url: "{{ font_url }}"
        dest: "{{ font_temp_zip }}"

    - name: Unzip CascadiaMono Nerd Font
      unarchive:
        src: "{{ font_temp_zip }}"
        dest: "{{ font_dest_dir }}"
        remote_src: yes

    - name: Refresh font cache
      command: fc-cache -f -v

    - name: Ensure KDE config directory exists
      file:
        path: "{{ kde_user_config_dir }}"
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '0755'

    - name: Set KDE font settings (10pt Cascadia Mono Nerd Font)
      ini_file:
        path: "{{ kde_user_config_dir }}/kdeglobals"
        section: General
        option: fixed
        value: "CaskaydiaCove Nerd Font Mono,10,-1,5,50,0,0,0,0,0"
        mode: '0644'
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        create: yes

    - name: Apply Breeze Dark theme
      ini_file:
        path: "{{ kde_user_config_dir }}/kdeglobals"
        section: General
        option: ColorScheme
        value: "BreezeDark"
        mode: '0644'
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"

    - name: Set IconTheme to Breeze Dark
      ini_file:
        path: "{{ kde_user_config_dir }}/kdeglobals"
        section: Icons
        option: Theme
        value: "breeze-dark"
        mode: '0644'
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"

    - name: Set CursorTheme to Breeze
      ini_file:
        path: "{{ kde_user_config_dir }}/kcminputrc"
        section: Mouse
        option: cursorTheme
        value: "Breeze"
        mode: '0644'
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"

    - name: Set LookAndFeel to BreezeDark
      ini_file:
        path: "{{ kde_user_config_dir }}/kdeglobals"
        section: KDE
        option: LookAndFeelPackage
        value: "org.kde.breezedark.desktop"
        mode: '0644'
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"


