---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Debian"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache/php
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Debian"

  - name: copy html for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: file_servers
  become: true
  tasks:

  - name: install samaba
    apt:
      name: samba
      state: latest
    when: ansible_distribution == "Debian"


- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Debian"

- hosts: workstations
  become: true
  tasks:

  - name: Download Terraform using curl to bypass Python HTTPS
    shell: curl -L -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/1.12.1/terraform_1.12.1_linux_amd64.zip
    args:
      creates: /tmp/terraform.zip

  - name: Unzip Terraform binary
    unarchive:
      src: /tmp/terraform.zip
      dest: /usr/local/bin/
      remote_src: yes
      mode: '0755'
