---

- hosts: all
  become: true
  tasks:

  - name: Installing required packages. 
    apt:
      name:
        - git
        - zsh
        - btop
        - wget
        - curl
      state: latest

  - name: Pulling zsh-syntax-highlighting
    git:
      repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
      dest: /usr/share/zsh-syntax-highlighting

  - name: Pulling zsh-autosuggestions
    git:
      repo: https://github.com/zsh-users/zsh-autosuggestions.git
      dest: /usr/share/zsh-autosuggestions

  - name: Deploying .zshrc config
    copy:
      src: /home/ashep/.zshrc
      dest: "/home/{{ ansible_user }}/.zshrc"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: '0644'

  - name: Setting ZSH as default shell.
    user:
      name: "{{ ansible_user }}"
      shell: /usr/bin/zsh

  - name: Cloning fzf repo
    git:
      repo: https://github.com/junegunn/fzf.git
      dest: "/home/{{ ansible_user }}/.fzf"
      update: yes

  - name: Installing fzf
    shell: |
      printf 'y\ny\ny\n' | ./install
    args:
      chdir: /home/{{ ansible_user }}/.fzf
      creates: /home/{{ ansible_user }}/.fzf/bin/fzf
    become_user: "{{ ansible_user }}"
