---

- hosts: all
  become: true
  pre_tasks:

  - name: updating repo caches
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Debian"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache/php
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Debian"

  - name: Start apache2
    tags: apache,httpd
    service:
      name: apache2
      state: started
      enabled: yes

  - name: change email for admin
    lineinfile:
      path: /etc/apache2/sites-available/000-default.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somewhere.net
    register: apache2

  - name: restart apache2
    tags: apache2
    service:
      name: apache2
      state: restarted
    when: apache2.changed

  - name: copy html for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: file_servers
  become: true
  tasks:

  - name: install samaba
    apt:
      name: samba
      state: latest
    when: ansible_distribution == "Debian"


- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Debian"

- hosts: workstations
  become: true
  tasks:

  - name: Download Terraform using curl to bypass Python HTTPS
    shell: curl -L -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/1.12.1/terraform_1.12.1_linux_amd64.zip
    args:
      creates: /tmp/terraform.zip

  - name: Unzip Terraform binary
    unarchive:
      src: /tmp/terraform.zip
      dest: /usr/local/bin/
      remote_src: yes
      mode: '0755'
