---
- name: Install zsh and configure for all users
  hosts: Debian_Workstations
  become: true

  vars:
    zshrc_path: ".zshrc"  # Path relative to playbook's files/ directory

  tasks:

    - name: Ensure required packages are installed
      apt:
        name:
          - git
          - zsh
          - btop
          - wget
          - curl
          - nala
        state: latest
        update_cache: yes

    - name: Clone zsh-syntax-highlighting
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: /usr/share/zsh-syntax-highlighting
        update: yes

    - name: Clone zsh-autosuggestions
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions.git
        dest: /usr/share/zsh-autosuggestions
        update: yes

    - name: Get list of local users (UID ≥ 1000 and valid shell)
      command: >
        awk -F: '$3 >= 1000 && $7 ~ /(bash|zsh|sh)$/ { print $1 }' /etc/passwd
      register: local_users_raw
      changed_when: false

    - name: Set fact for user list
      set_fact:
        local_users: "{{ local_users_raw.stdout_lines }}"

    - name: Deploy .zshrc config for each user
      copy:
        src: "{{ zshrc_path }}"
        dest: "/home/{{ item }}/.zshrc"
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: '0644'
      loop: "{{ local_users }}"
      loop_control:
        label: "{{ item }}"

    - name: Set zsh as default shell for each user
      user:
        name: "{{ item }}"
        shell: /usr/bin/zsh
      loop: "{{ local_users }}"

- name: Deploy KDE keyboard shortcuts to all local users
  hosts: Debian_Workstations
  become: true

  vars:
    shortcut_file: kglobalshortcutsrc
    users: "{{ lookup('pipe', \"awk -F: '$3 >= 1000 && $7 ~ /(bash|zsh|sh)$/ { print $1 }' /etc/passwd\") | split('\n') }}"

  tasks:

    - name: Ensure .config directory exists for each user
      file:
        path: "/home/{{ item }}/.config"
        state: directory
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: '0755'
      loop: "{{ users }}"
      when: item != 'nobody'

    - name: Deploy custom kglobalshortcutsrc for each user
      copy:
        src: "{{ shortcut_file }}"
        dest: "/home/{{ item }}/.config/kglobalshortcutsrc"
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: '0644'
      loop: "{{ users }}"
      when: item != 'nobody'

    - name: Reload KDE shortcuts via qdbus if X11 session active
      become: false
      shell: |
        qdbus org.kde.kglobalaccel /component/org.kde.konsole reloadConfig || true
      environment:
        DISPLAY: ":0"
        XAUTHORITY: "/home/{{ item }}/.Xauthority"
      loop: "{{ users }}"
      when: ansible_facts['env']['XDG_SESSION_TYPE'] == "x11"

- name: Set KDE Plasma wallpaper for all users
  hosts: Debian_Workstations
  become: true

  vars:
    wallpaper_path: "/usr/share/wallpapers/my_wallpaper.jpg"

  tasks:

    - name: Get list of users with home directories
      command: >
        awk -F: '$3 >= 1000 && $7 ~ /(bash|zsh|sh)$/ { print $1 }' /etc/passwd
      register: local_users_raw
      changed_when: false

    - name: Set fact with list of users
      set_fact:
        local_users: "{{ local_users_raw.stdout_lines }}"

    - name: Ensure wallpaper exists on remote
      copy:
        src: files/my_wallpaper.jpg
        dest: "{{ wallpaper_path }}"
        mode: '0644'

    - name: Modify Plasma config to set wallpaper for each user
      lineinfile:
        path: "/home/{{ item }}/.config/plasma-org.kde.plasma.desktop-appletsrc"
        regexp: '^Image='
        line: "Image=file://{{ wallpaper_path }}"
        create: yes
      become_user: "{{ item }}"
      loop: "{{ local_users }}"

    - name: Restart Plasma Shell to apply wallpaper for each user
      shell: |
        qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript \
          "var allDesktops = desktops(); for (i=0;i<allDesktops.length;i++) { d = allDesktops[i]; d.wallpaperPlugin = 'org.kde.image'; d.currentConfigGroup = Array('Wallpaper', 'org.kde.image', 'General'); d.writeConfig('Image', 'file://{{ wallpaper_path }}') }"
      become_user: "{{ item }}"
      environment:
        DISPLAY: ":0"
        XAUTHORITY: "/home/{{ item }}/.Xauthority"
      loop: "{{ local_users }}"

- name: Install CaskaydiaMono Nerd Font system-wide
  hosts: Debian_Workstations
  become: true

  vars:
    nerd_font_url: "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/CaskaydiaCove.zip"
    font_temp_dir: "/tmp/nerd-fonts"
    font_dest_dir: "/usr/share/fonts/truetype/caskaydia"

  tasks:

    - name: Ensure font destination directory exists
      file:
        path: "{{ font_dest_dir }}"
        state: directory
        mode: '0755'

    - name: Create temporary font download directory
      file:
        path: "{{ font_temp_dir }}"
        state: directory
        mode: '0755'

    - name: Download CaskaydiaMono Nerd Font zip
      get_url:
        url: "{{ nerd_font_url }}"
        dest: "{{ font_temp_dir }}/CaskaydiaCove.zip"
        mode: '0644'

    - name: Unzip font archive
      unarchive:
        src: "{{ font_temp_dir }}/CaskaydiaCove.zip"
        dest: "{{ font_dest_dir }}"
        remote_src: yes
        creates: "{{ font_dest_dir }}/CaskaydiaCove Nerd Font Complete Mono.ttf"

    - name: Set correct permissions on font files
      file:
        path: "{{ font_dest_dir }}"
        recurse: yes
        owner: root
        group: root
        mode: '0644'

    - name: Refresh font cache
      command: fc-cache -f -v
